// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bofrlvfxwuskfagubvde.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJvZnJsdmZ4d3Vza2ZhZ3VidmRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNjk2NjEsImV4cCI6MjA2NTc0NTY2MX0.8tioLK2mko5bEtCeNBs1t_pw4lxNQIQiHsN_JYres3Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);